/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PasswordStoreAppV3;
import PasswordStoreAppV3.models.MainPage;
import PasswordStoreAppV3.models.password.DataPassword;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        DataPassword.loadCSVData();
        new MainPage(80).draw();
    }
}
